[{$smarty.block.parent}]

[{block name="oegeoblocking_form_user_shipping_country"}]
	[{foreach from=$oViewConf->getCountryList() item=country key=country_id}]
		[{*In case it's invoice only country, it's being removed from dropdown list.*}]
		[{if $country->oeGeoBlockingIsInvoiceOnly()}]
			[{assign var="scriptToMarkCountryElement" value='$(\'#delCountrySelect option[value="'|cat:$country->oxcountry__oxid->value|cat:'"]\').remove();'}]
			[{oxscript add=$scriptToMarkCountryElement}]
		[{/if}]
	[{/foreach}]
[{/block}]
