<?php
/**
 * Copyright © OXID eSales AG. All rights reserved.
 * See LICENSE file for license details.
 */

return [
    'countryToShopData' => [
        'OXID' => '478ec8995365172e5e1da6852dfc0a76',
        'OXCOUNTRYID' => 'a7c40f632a0804ab5.18804076',
        'OXSHOPID' => 1,
        'PICKUP_ADDRESSID' => 'pickup_address_id',
        'PICKUP_ADDRESS_ACTIVE' => 1,
        'INVOICE_ONLY' => 1,
        'OXTIMESTAMP' => '2019-01-24 16:32:24',
    ],
    'productsData' => [
        'oxarticles' => [
            'OXID' => '1000',
            'OXSHOPID' => 1,
            'OXACTIVE' => 1,
            'OXARTNUM' => '1000',
            'OXTITLE' => 'Test product',
            'OXSHORTDESC' => 'Test product short desc',
            'OXPRICE' => 10,
            'OXUNITNAME' => 'kg',
            'OXUNITQUANTITY' => 2,
            'OXVAT' => NULL,
            'OXWEIGHT' => 24,
            'OXSTOCK' => 15,
            'OXSTOCKFLAG' => 1,
            'OXINSERT' => '2008-02-04',
            'OXTIMESTAMP' => '2008-02-04 17:07:29',
            'OXLENGTH' => 1,
            'OXWIDTH' => 2,
            'OXHEIGHT' => 2,
            'OXSEARCHKEYS' => 'search1000',
            'OXISSEARCH' => 1,
            'OXVARMINPRICE' => 50,
            'OXTITLE_1' => 'Test product',
            'OXSHORTDESC_1' => 'Test product short desc',
            'OXSUBCLASS' => 'oxarticle',
            'OXACTIVEFROM' => '2008-02-04 17:07:29',
            'OXACTIVETO' => '2600-02-04 17:07:29',
            'OXDELIVERY' => '2008-02-04',
        ],
    ],
    'pickupAddress' => [
        'OXID' => 'pickup_address_id',
        'OXADDRESSUSERID' => '',
        'OXCOMPANY' => 'Pickup address',
        'OXFNAME' => 'TestName',
        'OXLNAME' => 'TestSurname',
        'OXSTREET' => 'Test street',
        'OXSTREETNR' => '10',
        'OXCITY' => 'Freiburg',
        'OXCOUNTRY' => 'Germany',
        'OXCOUNTRYID' => 'a7c40f631fc920687.20179984',
        'OXZIP' => '111',
    ],
    'userAddress' => [
        'OXID' => 'user_defined_pickup_address_id',
        'OXUSERID' => 'oegeoblockingtestuser',
        'OXADDRESSUSERID' => '',
        'OXCOMPANY' => 'Some company',
        'OXFNAME' => 'TestName',
        'OXLNAME' => 'TestSurname',
        'OXSTREET' => 'Test street 2',
        'OXSTREETNR' => '10',
        'OXCITY' => 'Freiburg',
        'OXCOUNTRY' => 'Germany',
        'OXCOUNTRYID' => 'a7c40f631fc920687.20179984',
        'OXZIP' => '111',
    ],
    'user' => [
        'OXID' => 'oegeoblockingtestuser',
        'OXACTIVE' => 1,
        'OXRIGHTS' => 'user',
        'OXSHOPID' => 1,
        'OXUSERNAME' => 'testing_account@oxid-esales.local',
        'OXPASSWORD' => '13d726b9144af35f87b353e86185246fa4dc763f059d01e482d1360765ff3db96ec143df98c14df28b8d9414d40b5f32d090280c7d405a90d27de7f414437d7a',
        'OXPASSSALT' => '8f9c890adba62e6b8610544792b9eecc',
        'OXCUSTNR' => 1000,
        'OXFNAME' => 'FirstName',
        'OXLNAME' => 'LastName',
        'OXSTREET' => 'StreetName',
        'OXSTREETNR' => 'StreetNr',
        'OXZIP' => '79098',
        'OXCITY' => 'United Kingdom',
        'OXCOUNTRYID' => 'a7c40f632a0804ab5.18804076',
        'OXCREATE' => '2000-01-01 00:00:00',
        'OXREGISTER' => '2000-01-01 00:00:00',
        'OXBIRTHDATE' => '2000-01-01',
    ],
    'userAddressData' => [
        "UserSalutation" => 'Mrs',
        "UserFirstName" => "user name_šÄßüл",
        "UserLastName" => "user last name_šÄßüл",
        "CompanyName" => "user company_šÄßüл",
        "Street" => "user street_šÄßüл",
        "StreetNr" => "111",
        "ZIP" => "1234",
        "City" => "user city_šÄßüл",
        "CountryId" => 'United Kingdom',
    ],
    'userData' => [
        "userUstIDField" => "",
        "userMobFonField" => "111-111111",
        "userPrivateFonField" => "11111111",
        "userBirthDateDayField" => rand(10, 28),
        "userBirthDateMonthField" => rand(10, 12),
        "userBirthDateYearField" => rand(1960, 2000),
    ],
    'userLoginData' => [
        "userLoginNameField" => "test_registration@oxid-esales.local",
        "userPasswordField" => 'useruser',
    ],
];
