<?php  //[STAMP] 10cdf1c01fc410fd78b1833ddc3b5492
namespace OxidEsales\GeoBlocking\Tests\Codeception\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
